services:
  neo4j:
    image: neo4j:2025-community
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - type: bind
        source: $EAE_DATA_DIR/graph
        target: /data
